# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node Build App

on:
  push:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: ./package-lock.json
    - name: npm install and build
      run: |
        npm install esbuild
        npm i
        npm run generate-openapi
        npx ng build --configuration development --source-map false --aot true --optimization true --base-href /${{ github.event.repository.name }}/app/
    - name: Copy dist to webserver static
      run: |
        rm -rf ./docs/app
        cp -r ./dist/${{ github.event.repository.name }}/browser ./docs/app
    - name: Commit static
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
        # Stage the changes first
        git add --force ./docs/app
        git add --force ./docs/openapi.json

        # Check if there are any changes to commit after staging
        if [[ -n $(git status --porcelain) ]]; then
          git commit -m "Automated pages app build"
          git push
        else
          echo "No changes to commit"
        fi
