name: Angular CI - Test Multiple Browsers

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    # Use a matrix strategy to run tests on different OS and Node versions
    strategy:
      matrix:
        # Run tests with different browsers using headless mode
        # Ensure Browser is configured in your karma.conf.js
        browser: [ChromeHeadlessCI, FirefoxHeadlessCI]
        include:
          # - os: macos-latest
          #   node-version: 22.x
          #   shell: bash
          - os: ubuntu-latest
            node-version: 22.x
            shell: bash
          # - os: windows-latest
          #   node-version: 22.x
          #   shell: cmd

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Cache node modules for faster builds

      - name: Install Dependencies
        run: npm ci

      - name: Install Firefox Dependencies (Windows)
        if: ${{ startsWith(matrix.os, 'windows') && startsWith(matrix.browser, 'Firefox') }}
        run: |
          choco install firefox

      - name: Install Firefox macOS
        if: ${{ startsWith(matrix.os, 'macos') && startsWith(matrix.browser, 'Firefox') }}
        # macOS runners usually have Safari and Chrome pre-installed.
        # Add steps here only if you need specific versions or other browsers not pre-installed.
        run: |
          brew install --cask firefox

      - name: Run Tests - ${{ matrix.browser }}
        run: npm run test-ci -- --browsers ${{ matrix.browser }}
        
